project_name: image_similarity_probability
experiment_name: baseline
track_in_clearml: true


name_model: 'vit_base_patch14_dinov2'

optimizer_config:
  name: Adam
  lr: 1e-3
  weight_decay: 0

scheduler_config:
    warmup_steps: 400
    num_cycles:  1

trainer_config:
  min_epochs: 4
  max_epochs: 64
  check_val_every_n_epoch: 1
  log_every_n_steps: 64
  devices: 1
  accelerator: gpu
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: false
  fast_dev_run: False
  default_root_dir: null
  detect_anomaly: false

data_config:
  dataset_dir: data/dataset
  img_size:
  - 224
  - 224
  batch_size: 4
  data_split:
  - 0.8
  - 0.1
  - 0.1
  num_workers: 1
  pin_memory: true
  seed: 13
