project_name: image_similarity_probability
experiment_name: baseline
track_in_clearml: true

name_model: 'vit_base_patch14_dinov2'

optimizer_config:
  name: Adam
  lr: 1e-3
  weight_decay: 0.01

trainer_config:
  min_epochs: 4
  max_epochs: 64
  check_val_every_n_epoch: 1
  log_every_n_steps: 64
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: false
  fast_dev_run: false
  default_root_dir: null
  detect_anomaly: false
data_config:
  dataset_dir: /data
  img_size:
  - 256
  - 256
  batch_size: 32
  data_split:
  - 0.8
  - 0.2
  num_workers: 12
  pin_memory: true
